### ISSUE TITLE
Exporting genotype matrix with snp.allele ids instead of 0,1,2 genotype codes from gds file

### ISSUE THREAD

**Issue by jpfontenelle** [zhengxwen/SNPRelate#101]
Hello all,

Sorry for what seems to be a very basic question.

I need to export a genotype table with individuals as rows and snps as columns but instead of using the 0,1,2 codes for genotype, I need the bi allelic information (snp.allele). 

When I run
`read.gdsn(index.gdsn(my.gds, "genotype"))`
I get the genotype table with the dimensions I need, but with the 0,1,2 code

But when I run
`read.gdsn(index.gdsn(my.gds, "snp.allele"))`
I get a string/list as long as the number of snps I have in the gds, but no individual info. It appears to be a single line only.

I wonder what would be the proper way generate a genotype table indXsnp with bi allelic info instead of 0,1,2

Thanks

**Comment by smgogarten** [comment]
You can do this with the GWASTools package:
```
> library(GWASTools)
> file <- system.file("extdata", "illumina_geno.gds", package="GWASdata")
> gds <- GdsGenotypeReader(file)
> genoData <- GenotypeData(gds)
> geno <- getGenotype(genoData, char=TRUE)
> dim(geno)
[1] 3300   77
> geno[1:5,1:5]
     [,1]  [,2]  [,3]  [,4]  [,5] 
[1,] NA    NA    NA    NA    NA   
[2,] "C/C" "C/C" "C/C" "C/C" "C/C"
[3,] "C/C" "C/C" "C/C" "C/C" "C/T"
[4,] "C/T" "C/T" "C/T" "C/T" "C/C"
[5,] "C/C" "C/C" "C/C" "C/C" "C/C"
```

**Comment by jpfontenelle** [comment]
Thanks! Very helpful.
Cheers
