### ISSUE TITLE
add.gdsn not work correctly 

### ISSUE THREAD

**Issue by lian0090** [zhengxwen/SNPRelate#13]
When I try to add some data into my gdsn object, R reports this error 
add.gdsn(genofile, "try", "da") : Invalid argument

**Comment by zhengxwen** [comment]
Can you show me the complete code?

**Comment by jliberto2** [comment]
Hi Zhengxweng, I hope it is okay to post this on a closed issue, but I am I am also having the same issue.  I am currently working with a small sample dataset.  The code seems to work just fine until I try to add my new data frame in.  I will post my code below:

snpgdsVCF2GDS("snps.first30.5ind.vcf","snps.first30.5ind.gds",verbose=T)
genofile=openfn.gds("snps.first30.5ind.gds")
RV <- snpgdsPCA(genofile, num.thread=2)
samp.annot<-data.frame(pop.group = c("EUR","EUR","EUR","EUR","EUR","EUR"))
add.gdsn(genofile, "sample.annot", samp.annot)

**Comment by zhengxwen** [comment]
Please open the GDS file with a writable option:
```R
genofile = openfn.gds("snps.first30.5ind.gds", readonly=FALSE)
```
and,
```R
add.gdsn(genofile, "sample.annot", val=samp.annot)
```

Also please try installing the latest version of `gdsfmt` and `SNPRelate`.

**Comment by jliberto2** [comment]
Thank you for your quick response.  Updating my R to version 3.4.2 allowed me to update SNPRelate to 1.4.2 and gdsfmt to 1.6.2, which the key to my problem.  I hope you have a very nice evening and again, thank you for your help.
