### ISSUE TITLE
what method of clustering do you use?

### ISSUE THREAD

**Issue by orchid00** [zhengxwen/SNPRelate#16]
According to this: http://www.inside-r.org/packages/cran/SNPRelate/docs/snpgdsHCluster
the method is "complete"

but when I check my cluster object it says "average"

cluster_ <- snpgdsHCluster(dist_, need.mat=TRUE, hang=-1)

attributes(cluster_$hclust)
$names
[1] "merge"       "height"      "order"       "labels"      "method"     
[6] "call"        "dist.method"

(cluster_$hclust$method)
[1] "average"

(cluster_27$hclust$dist.method)
NULL

This is important for my analysis would you please confirm? thanks!
the last PDF https://www.bioconductor.org/packages/release/bioc/manuals/SNPRelate/man/SNPRelate.pdf 
has no details.

I would also like to know what kind of distance metric is used for snpgdsDiss.

**Comment by zhengxwen** [comment]
This is a typo. `snpgdsHCluster()` calls `hclust()` with`method="average"`.

`snpgdsDiss()` returns a distance metric based on the estimated Fst at the individual level. You might cite this paper for `snpgdsDiss()`:
*Weir BS, Zheng X. SNPs and SNVs in Forensic Science. 2015. Forensic Science International: Genetics Supplement Series.*
It returns $1 - \beta_ij$ (\beta is described in *SNPs and SNVs in Forensic Science. 2015*)

**Comment by orchid00** [comment]
Thank you! great package btw :+1:
