### ISSUE TITLE
Exporting snpgdsCutTree data into a JSON format?

### ISSUE THREAD

**Issue by brspurri** [zhengxwen/SNPRelate#18]
Is there any supported (or unsupported) way to create a dendrogram using:
```
dissMatrix  <-  snpgdsDiss(genofile , sample.id=NULL, snp.id=NULL, autosome.only=TRUE,remove.monosnp=TRUE, maf=NaN, missing.rate=NaN, num.thread=10, verbose=TRUE)
snpHCluster <-  snpgdsHCluster(dissMatrix, sample.id=NULL, need.mat=TRUE, hang=0.25)
cutTree <- snpgdsCutTree(snpHCluster, z.threshold=15, outlier.n=5, n.perm = 5000, samp.group=NULL,col.outlier="red", col.list=NULL, pch.outlier=4, pch.list=NULL,label.H=FALSE, label.Z=TRUE, verbose=TRUE)
```

And export the `cutTree` to a hierarchial `JSON` format? I would love to be able to display the graphs in [d3](http://d3js.org/), but not sure how to go about starting the format conversions.

Does anyone have any pointers?

**Comment by zhengxwen** [comment]
I google "R dendrogram JSON", and find:
https://gist.github.com/markvanderloo/13b4447e14e642635984

Call
```R
s <- d3dendrogram(cutTree$dendrogram)
cat(s, file="dendrogram.html", sep="\n")
```
It is able to create a html file `dendrogram.html` to show D3 dendrogram.

**Comment by brspurri** [comment]
Wow, yeah, this is an awesome start. Thanks!
