### ISSUE TITLE
SNP ID

### ISSUE THREAD

**Issue by lilnet** [zhengxwen/SNPRelate#20]
When loading with a vcf file, it seems that the SNP ID attached to each loci is lost when converted to gds. 
Is there anyway to retain the SNP ID for each loci when loading from a vcf file format.

Many thanks!

**Comment by zhengxwen** [comment]
Call `snpgdsVCF2GDS()` to convert a VCF file to a GDS file, and see `snp.rs.id` in the GDS file.
