### ISSUE TITLE
Description file: Depends and Suggests

### ISSUE THREAD

**Issue by thierrygosselin** [zhengxwen/SNPRelate#22]
Hi Xiuwen,
I think `BiocInstaller` should be listed in `Imports` or `Depends` because with a fresh R install, it is requested. Maybe because of `gdsfmt `  or `BiocGenerics `?

Cheers
Thierry

**Comment by zhengxwen** [comment]
SNPRelate is a Bioconductor package.
Please follow the BioC installation instruction (http://www.bioconductor.org/packages/release/bioc/html/SNPRelate.html)

```
source("https://bioconductor.org/biocLite.R")
biocLite("SNPRelate")
```
