### ISSUE TITLE
The method you take to calculate PCA, IBD and IBS

### ISSUE THREAD

**Issue by nottwy** [zhengxwen/SNPRelate#26]
SNPrelate is a very fast and useful tool so I decide to learn it carefully.

But I find SNPrelate tells little about the way it calculates. Now I want to know more about the detail of PCA, IBD and IBS analysis SNPRelate does. There are lots of manuscripts telling stories about PCA, IBD and IBS but I don't know what's the way that SNPRelate takes. I want to know more about how snp data is transformed into statistic results in SNPRelate. 

Can you supply these information for us?

**Comment by zhengxwen** [comment]
Please take a look at the help document of each SNPRelate function:
http://www.bioconductor.org/packages/release/bioc/manuals/SNPRelate/man/SNPRelate.pdf
There are references in each help document.

For example,
snpgdsPCA:
```
Patterson N, Price AL, Reich D. Population structure and eigenanalysis. PLoS Genet. 2006 Dec;2(12):e190.
```

**Comment by nottwy** [comment]
I don't understand what's the difference between PCA and IBS-multidimensional scaling analysis.
I think they look the same.
I have looked at the help document of snpgdsIBS, but I haven't found related references.
