### ISSUE TITLE
R Error : '...' used in the wrong context

### ISSUE THREAD

**Issue by marieBvr** [zhengxwen/SNPRelate#30]
Hi, 
I'm following your tutorial on http://corearray.sourceforge.net/tutorials/SNPRelate/#snpgdscreategeno with my own gds file.
I encounter an error with the following part :
`
for (i in 1:length(sample.id))
{
    g <- ...
    write.gdsn(var.geno, g, start=c(1,i), count=c(-1,1))
}
`

It sends me : R Error : '...' used in the wrong context

Any idea how to resolve this ?

Thanks
Marie

**Comment by zhengxwen** [comment]
You should write your code in the place of `...`.
E.g., `g <- rep(0, n_snp)` where `n_snp` is the number of SNPs.

**Comment by marieBvr** [comment]
It works.
Thanks
