### ISSUE TITLE
snpgdsOpen error

### ISSUE THREAD

**Issue by nottwy** [zhengxwen/SNPRelate#32]
The only command I have run was:
snpgdsVCF2GDS(merged_snp.fn,"snp.gds",method=c("biallelic.only"))
It gave me an error message which said:

Parsing "merged_snp.hard_filtered.vcf" ...
Error: Genotype code is out of range "1707194".
FILE: merged_snp.hard_filtered.vcf
LINE: 1437733, COLUMN: 19, 1707194

So what's wrong with it?
3ku.

**Comment by zhengxwen** [comment]
It said "1707194" is not a valid genotype.
Please check your VCF file (LINE: 1437733, COLUMN: 19).

**Comment by nottwy** [comment]
I also found there seems to be an I/O problem which causes the format of my vcf to be wrong just now.
Thank u for your so quick reply!
