### ISSUE TITLE
the definition of missing rate

### ISSUE THREAD

**Issue by nottwy** [zhengxwen/SNPRelate#33]
Sorry to disturb you again.

Could you please explain the meaning of missing.rate?
What does it mean?

**Comment by zhengxwen** [comment]
missing.rate is the proportion of missing genotypes.

**Comment by nottwy** [comment]
missing.rate = M/N
where M is the number of samples whose genotype misses here and N is the total number of samples.
Is it correct?

**Comment by zhengxwen** [comment]
yes
