### ISSUE TITLE
Output the LD-pruned GDS from SNPRelate for phylogenetic analysis in SNPyhlo

### ISSUE THREAD

**Issue by Tman3** [zhengxwen/SNPRelate#35]
I performed PCA analysis on a vcf file after being LD-pruned in SNPRelate. 
Would like to determine whether I could output such GDS file from SNPRelate so I could use it as input for SNPhylo.
My goal is to use the same LD-pruned GDS file or the revised list of SNPs in the SNPhylo analysis.
Your advice is appreciated.

**Comment by zhengxwen** [comment]
I don't have such function currently.
But you can call `snpgdsGDS2BED()` with a set of selected SNPs to create a BED file, and then call `snpgdsBED2GDS()`.

**Comment by nute11a** [comment]
Hello!
I am actually trying to do the same thing as Tman3 (so a feature would definitely be great!) Unfortunately, I tried to do what was suggested (convert selected SNPs to BED file, and then import the genotypes) but got this error:

Converting from GDS to PLINK binary PED:
Working space: NUM samples, 6826 NUM SNPs
Error in if ((opt$autosome.start == 1) & (opt$autosome.end == 22)) { : 
  missing value where TRUE/FALSE needed

I can't seem to find much about resolving this error. Have you seen it before, and do you have any suggestions moving forward?

Thanks!

**Comment by zhengxwen** [comment]
See the function `snpgdsCreateGenoSet()` in the package SNPRelate.
I have provided such function in the package.
