### ISSUE TITLE
snpgdsLDpruning

### ISSUE THREAD

**Issue by jjpadilla** [zhengxwen/SNPRelate#38]
Hi, i would like to do pruning based on relatedness of my samples. I ran the code following the paper of Reed et al, 2015. 

snpSUB <- snpgdsLDpruning(genofile, ld.threshold = ld.thresh, 
                          sample.id = geno.sample.ids, # only analyze the filtered samples
                          snp.id = colnames(genotype)) # only analyze the filtered snps

Unfortunately, i always giot this error message. could you help me on solving this? Thanks in advance!

Error in .InitFile2(cmd = paste(ifelse(inherits(gdsobj, "SeqVarGDSClass"),  : 
  Some of sample.id do not exist!

**Comment by zhengxwen** [comment]
Some of the sample IDs you passed to the function `snpgdsLDpruning()` are not in the GDS file.
please read the sample id:
```R
samp_id <- read.gdsn(index.gdsn(genofile, "sample.id"))
```
to see which sample IDs you can use in the GDS file.
