### ISSUE TITLE
Does snpgdsLDpruning calculate squared correlation coefficient?

### ISSUE THREAD

**Issue by wvictor14** [zhengxwen/SNPRelate#42]
Hi, 

Quick question, does snpgdsLDpruning  calculate squared correlation coefficient or the correlation coefficient? I'm guessing the former but I'm not sure based on the description of the help file.

Thanks,
Victor

**Comment by zhengxwen** [comment]
It is the correlation coefficient.
When you run `snpgdsLDpruning()`, it shows:
```
    |LD| threshold: 0.2
```
indicating the LD value could be negative, so it is correlation coefficient.
