### ISSUE TITLE
snpgdsFs fuction/Issue in returning SNP ids list used in the analysis

### ISSUE THREAD

**Issue by elenadehnavi** [zhengxwen/SNPRelate#43]
Hi Xiuwen,
I'm using SNPRelate package. Using snpgdsFs fuction I can not find the SNP ids used in the analysis which I expect to be returned in out put (manual page 29). Running the example dataset of manual this issue existed.
Thanks
Elena

**Comment by zhengxwen** [comment]
```R
     snpgdsFst(gdsobj, population, method=c("W&C84", "W&H02"), sample.id=NULL,
         snp.id=NULL, autosome.only=TRUE, remove.monosnp=TRUE, maf=NaN,
         missing.rate=NaN, with.id=FALSE, verbose=TRUE)
```
`with.id`: if ‘TRUE’, the returned value with ‘sample.id’ and ‘sample.id’

You should set `with.id=TRUE` in `snpgdsFst()`.

**Comment by elenadehnavi** [comment]
Great! Thanks.
