### ISSUE TITLE
snpgdsGDS2PED() sample annotation

### ISSUE THREAD

**Issue by AAvalos82** [zhengxwen/SNPRelate#47]
Is it intended for the function snpgdsGDS2PED() to discard sample annotation fields from the GDS when creating corresponding PED files?

I have a snp GDS where I have added a data frame containing phenotype and family IDs manually following the [tutorial](https://bioconductor.org/packages/release/bioc/vignettes/SNPRelate/inst/doc/SNPRelateTutorial.html) but when I try to output PLINK format files it seems to not consider any of the annotation fields. The result is a PED file where annotation columns are 0-filled (or -9 in the case of the phenotype).

**Comment by smgogarten** [comment]
You could try using plinkWrite() in the GWASTools package. You would need to create a ScanAnnotationDataFrame object with your annotation and then combine it with the GDS in a GenotypeData object.

**Comment by AAvalos82** [comment]
Thank you, that approach worked once I realized I was hitting the "chromosome labels are hard-coded" wall. Since I study a non-model organism, that wall and I are old friends.
