### ISSUE TITLE
details of snpgdsLDpruning required

### ISSUE THREAD

**Issue by thierrygosselin** [zhengxwen/SNPRelate#48]
Hi,

In the function documentation of `SNPRelate::snpgdsLDpruning`, details are given on the sliding window implementation, but what is lacking in the detail section: the pruning process.

e.g. for a pair of SNPs in linkage lets say the r = 0.9. The pruning process will keep only 1 SNP.

**Question** 
how did you implement this selection process ? Is it random selection or is it implemented based on SNP with higher MAF or lower missing rate? (because you do start the detail section with those statistics). 

Best
Thierry

**Comment by zhengxwen** [comment]
It is a random selection.

**Comment by thierrygosselin** [comment]
thanks for the details
