### ISSUE TITLE
Using SNPRelate Results to prune VCF files

### ISSUE THREAD

**Issue by TrinityConn** [zhengxwen/SNPRelate#51]
I am new to using SNPRelate to analyze my data --- I pruned my SNPS for LD and want to filter my original VCF files according to the pruned data set from SNPRelate (for further use in other programs). However, the SNP ids coming out of SNPRelate are obviously not the same format  --- is there a way to reformat the snpset.ids coming out of SNPRelate so I can use it as a single line document to filter through vcf/bcf tools?

**Comment by zhengxwen** [comment]
If you used VCF/BCF, would you please try [SeqArray](https://github.com/zhengxwen/SeqArray)?
