### ISSUE TITLE
PCA with different symbols (pch)

### ISSUE THREAD

**Issue by mullerbsf** [zhengxwen/SNPRelate#64]
Dear Zheng, 

I am using the SNPRealte to generate a PCA.
I want to use different symbols (pch) in the plot, but it was not working when I tried to add another symbol.

Please see my scripts:

# PCA plot using only pch=20
pdf("PCA_PC1_2_with_pop_info_EVT_Algae_CRISP_4206variants_38samples.pdf")
col.list = c("darkgreen","green","darkred","red","darkblue","blue","black",
			"darkolivegreen","darkolivegreen1","darkslategray4","darkslategray1","darksalmon","salmon","gray")
par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
plot(tab$EV2, tab$EV1, col=col.list[as.integer(tab$pop)], pch=20,
		xlab="PC 2 (2.9%)", ylab="PC 1 (4.0%)", main="PCA of EVT Algae")
legend("right", inset=c(-0.35,0), ncol=1, pch=20, 
		c("CW_A_Dark","CW_A_Frozen","CW_B_Dark","CW_B_Frozen","CW_C_Dark","CW_C_Frozen","CW_control",
		"WT_A_Dark","WT_A_Frozen","WT_B_Dark","WT_B_Frozen","WT_C_Dark","WT_C_Frozen","WT_control"), 
		col=col.list[1:nlevels(tab$pop)])
dev.off()

[PCA_PC1_2_with_pop_info_EVT_Algae_CRISP_4206variants_38samples.pdf](https://github.com/zhengxwen/SNPRelate/files/3776292/PCA_PC1_2_with_pop_info_EVT_Algae_CRISP_4206variants_38samples.pdf)

The colors of the plot and legend are correct.

Next, when I am trying to add another symbol (pch=18):

# PCA plot using pch=20 and pch=18
pdf("test_PCA_PC1_2_with_pop_info_EVT_Algae_CRISP_4206variants_38samples.pdf")
col.list = c("darkgreen","green","darkred","red","darkblue","blue","black",
			"darkolivegreen","darkolivegreen1","darkslategray4","darkslategray1","darksalmon","salmon","gray")
par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
plot(tab$EV2, tab$EV1, col=col.list[as.integer(tab$pop)], 
		pch=c(20,20,20,20,20,20,20,18,18,18,18,18,18,18), 
		xlab="PC 2 (2.9%)", ylab="PC 1 (4.0%)", main="PCA of EVT Algae")
legend("right", inset=c(-0.35,0), ncol=1, pch=c(20,20,20,20,20,20,20,18,18,18,18,18,18,18), 
		c("CW_A_Dark","CW_A_Frozen","CW_B_Dark","CW_B_Frozen","CW_C_Dark","CW_C_Frozen","CW_control",
		"WT_A_Dark","WT_A_Frozen","WT_B_Dark","WT_B_Frozen","WT_C_Dark","WT_C_Frozen","WT_control"), 
		col=col.list[1:nlevels(tab$pop)])
dev.off()

[test_PCA_PC1_2_with_pop_info_EVT_Algae_CRISP_4206variants_38samples.pdf](https://github.com/zhengxwen/SNPRelate/files/3776294/test_PCA_PC1_2_with_pop_info_EVT_Algae_CRISP_4206variants_38samples.pdf)

In this case, I was able to change the symbols (pch) correctly in the legend. However, the plot is not following the order of the legend.

How can I generate the plot and the legend following the same colors and symbols?

Thank you!

**Comment by zhengxwen** [comment]
`tab` is a `data.frame`.
Could you please put `pch` and `col` into the data frame `tab`? So you can check the order of samples, pch and colors.

**Comment by mullerbsf** [comment]
It works. Thank you!
