### ISSUE TITLE
traceXTX is NaN for fastPCA

### ISSUE THREAD

**Issue by mchughc** [zhengxwen/SNPRelate#65]
We are attempting to run fastPCA with relatives. It appears that the TraceXTX object is set to NaN for fastPCA, causing the projection snp and samp loading runs to return NaN for all samples. Can you implement a fastPCA trace as well so that fastPCA runs with unrelated samples and relatives?
Thank you!

**Comment by zhengxwen** [comment]
It is easy to fix "TraceXTX", but I need time to figure out the eigenvalues of fastPCA (it is not correctly calculated now), since `snpgdsPCASampLoading()` also need eigenvalues.

**Comment by mchughc** [comment]
ok! thanks for working on it. if it helps, here's the fastSKAT paper that outlines the 'fast' eigenvalues, 'fast' trace and some other things. https://onlinelibrary.wiley.com/doi/full/10.1002/gepi.22136

**Comment by zhengxwen** [comment]
It is fixed in SNPRelate_1.12.1.

Best,

Xiuwen
