### ISSUE TITLE
snpgdsLDpruning gives different number of filtered variants every time.

### ISSUE THREAD

**Issue by VenithaB** [zhengxwen/SNPRelate#66]
The original number of variants in my gds file is 32,058.

`File: file.gds (657.8K)`
`[  ] *`
`|--+ sample.id   { Str8 50 LZMA_ra(119.2%), 305B }`
`|--+ snp.id   { Int32 32058 LZMA_ra(7.59%), 9.5K }`
`|--+ snp.rs.id   { Str8 32058 LZMA_ra(14.8%), 119.4K }`
`|--+ snp.position   { Int32 32058 LZMA_ra(46.4%), 58.2K }`
`|--+ snp.chromosome   { Str8 32058 LZMA_ra(0.07%), 293B }`
`|--+ snp.allele   { Str8 32058 LZMA_ra(18.9%), 39.1K }`
`|--+ genotype   { Bit2 50x32058, 391.3K } *`
`\--+ snp.annot   [  ]`
`   |--+ qual   { Float32 32058 LZMA_ra(30.0%), 37.6K }`
 `  \--+ filter   { Str8 32058 LZMA_ra(0.46%), 153B }`

Every time I run `snpgdsLDpruning` I get a different number of variants. The command I use is:

`snpset <- snpgdsLDpruning(genofile, ld.threshold = 0.5, autosome.only = F, method = "r", remove.monosnp = F, slide.max.bp = 50000)`

Why does this happen? Is this normal behaviour?

**Comment by zhengxwen** [comment]
See the help file of `snpgdsLDpruning`:
     The pruning algorithm on a chromosome is described as follows (n
     is the total number of SNPs on that chromosome):

     1) Randomly select a starting position i (‘start.pos="random"’),
     i=1 if ‘start.pos="first"’, or i=last if ‘start.pos="last"’; and
     let the current SNP set S={ i };

     2) For each right position j from i+1 to n: if any LD between j
     and k is greater than ‘ld.threshold’, where k belongs to S, and
     both of j and k are in the sliding window, then skip j; otherwise,
     let S be S + { j };

     3) For each left position j from i-1 to 1: if any LD between j and
     k is greater than ‘ld.threshold’, where k belongs to S, and both
     of j and k are in the sliding window, then skip j; otherwise, let
     S be S + { j };

     4) Output S, the final selection of SNPs.
