### ISSUE TITLE
varprop interpretation

### ISSUE THREAD

**Issue by MaVdb** [zhengxwen/SNPRelate#67]
The PCA analysis outputs varprop = proportion of variance for each principal component. 

What is the mathematics behind varprop, the proportion of variance? 

To calculate the proportion of total variance each principal component explains, I divide the eigenvalue of the principal component by the sum of all eigenvalues. 
This proportion is different than varprop. 

Thanks in advance!

**Comment by zhengxwen** [comment]
Which function exactly do you use?
Show me `sessionInfo()`

**Comment by MaVdb** [comment]
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Belgium.1252  LC_CTYPE=Dutch_Belgium.1252    LC_MONETARY=Dutch_Belgium.1252 LC_NUMERIC=C                  
[5] LC_TIME=Dutch_Belgium.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SNPRelate_1.18.1 gdsfmt_1.20.0   

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    knitr_1.28     xfun_0.12     


-----

# Open the GDS file
genofile <- snpgdsOpen(snpgdsExampleFileName())

set.seed(1000)

# Try different LD thresholds for sensitivity analysis
snpset <- snpgdsLDpruning(genofile, ld.threshold=0.2)

# Get all selected snp id
snpset.id <- unlist(snpset)
    
# Run PCA
pca <- snpgdsPCA(genofile, snp.id=snpset.id, num.thread=2)

pca_var<- round(pca$varprop*100, 2)
  pca_var[1:10] # 10.25  5.53  1.03  0.98  0.88  0.77  0.76  0.75  0.74  0.73
  sum(pca_var[1:4]) # 17.79
  sum(pca_var[1:32]) # 36.88

**My question is related to varprop --> how are these numbers obtained (0.1025,0.0553...)**
  
pca_eigenvalues <- data.frame(pca$eigenval,
                    stringsAsFactors = FALSE)
Eigenvalues <- subset(pca_eigenvalues,pca_eigenvalues$pca.eigenval!="NaN")

sum(Eigenvalues) # 102.4497
PropVar_PC1 <- 28.494488/(sum(Eigenvalues))      # 0.278

**The eigenvalue of first PC is 28.49, to get the variance explained by the first principal component, I divide the eigenvalue by the sum of all eigenvalues. This results in 0.278 ==> 27.8% of total variance is explained by first principal component**

**Comment by zhengxwen** [comment]
You misunderstand `pca_eigenvalues$pca.eigenval`.
`snpgdsPCA()` only calculate top 32 eigenvalues. You cannot sum these 32 eigenvalues.

**Comment by MaVdb** [comment]
Where do the numbers of pca$varprop comes from, what is the mathematics behind it?

**Comment by zhengxwen** [comment]
varprop = eigenvalue[1:32] / sum(all eigenvalues)
sum(all eigenvalues) could be calculated by other approaches, without enumerating all eigenvalues.

**Comment by MaVdb** [comment]
Thank you for your answer. How is sum(all eigenvalues) then calculated and how many eigenvalues are included in this sum?

**Comment by zhengxwen** [comment]
the number of eigenvalues  = # of samples
sum(all eigenvalues) = pca$eigenval[1] / pca$varprop[1]

**Comment by Guillefriis** [comment]
Hi,

I'm also interested on this. If sum(all eigenvalues) = pca$eigenval[1] / pca$varprop[1] then we are back to the previous question: how are varprop[1:32] computed? There is at least one euqotion missing.
