### ISSUE TITLE
snpgdsIBS: calculation method?

### ISSUE THREAD

**Issue by kroluk** [zhengxwen/SNPRelate#71]
Hi,

With what method is used for genome-wide pairwise identity-by-state calculation with snpgdsIBS()? I couldn't find this in the documentation, the tutorial or the publication. Could you please provide a formula or a reference for this?

Best Regards
Lukas

**Comment by zhengxwen** [comment]
genotype g = {0, 1, 2}, IBS = | g_1 - g_2 |, where g_1 is the first individual, g_2 is the second individual.

**Comment by kroluk** [comment]
Hi Xiuwen

Thanks for your reply. Unfortunately, I am still confused. Maybe I misunderstood something but I think the formula you supplied is incorrect. According to your formula, e.g. two completely related individuals (i.e. clones) would have an IBS coefficient of zero, but it should be one according to the results of snpgdsIBS() 

If I use the following formula across all loci (adapted from http://www.popgen.dk/angsd/index.php/PCA_MDS):
IBS[g1,g1] = sum( f(g,m) ) / M
         where g1 and g2 are the first and the second individual,
         m is the allele at the respective locus (m = {0,1,2}),
         M is the total number of loci,
         f(g,m) = 1, if  m[g1] = m[g2]
      and 
        f(g,m) = 0, if m[g1] != m[g2]
I obtain very similar results compared to snpgdsIBS() (differences around 0.01). 

The thing is, I used snpgdsIBS() to calculate IBS for a current manuscript, where it will of course be cited. However, I feel like I should supply a correct formula as well.

Thanks in advance

Lukas

**Comment by zhengxwen** [comment]
Sorry about the confusion. It should be IBS = 1 - | g_1 - g_2 |/2.
See https://www.youtube.com/watch?v=NRiI1RbE_-I

**Comment by kroluk** [comment]
Thanks a lot, this clears it up.

Cheers
Lukas
