### ISSUE TITLE
snpgdsVCF2GDS not recognizing contigs

### ISSUE THREAD

**Issue by cinnamon259** [zhengxwen/SNPRelate#73]
I am attempting to convert a VCF file to GDS with the following code:

snpgdsVCF2GDS(vcf.fn="myvcf.vcf", 
              out.fn="myvcf.gds",
              method = c("biallelic.only"),
              compress.annotation="ZIP.max",
              snpfirstdim=FALSE, verbose=TRUE)
snpgdsSummary("myvcf.gds")

When I try to look at the summary, I get the error "Error in sprintf("The SNP positions are not in ascending order on chromosome %d.",  : invalid format '%d'; use format %s for character objects

I used this same script and same vcf file on August 17th, 2020 with no issues. However, today I got this error. My data is aligned to a genome that is organized by contigs, not chromosomes. I checked the vcf file for any errors or hidden formatting, I used the snpgdsOption() to specify the starting and ending contig numbers, and ignored the contig number prefix, so only the number was used. I can still use the snpgdsPCA() function without issue, but have not been able to generate the snpgdSummary.  I am using v1.12.2, with R 3.4.3. Any insight into this issue would be greatly appreciated. Thank you!

**Comment by mergi-2674** [comment]
dear cinnamon259
I faced the same problem currently and i just made it work. Just change these snpgdsVCF2GDS(myvcf.fn,
myvcf.out,
method = c("biallelic.only"),
compress.annotation="LZMA_RA",
snpfirstdim=FALSE, verbose=TRUE)
snpgdsSummary("myvcf.fn") or snpgdsSummary(myvcf.fn)
cheers!

**Comment by zhengxw-ab** [comment]
Please use `seqVCF2GDS()` in the SeqArray package to handle the contigs data.
