### ISSUE TITLE
'snpgdsCombineGeno' should support merging different SNP sets in future!

### ISSUE THREAD

**Issue by zhengxwen** [zhengxwen/SNPRelate#8]

**Comment by michaelpreuss** [comment]
That's exactly what I need :).
However,  it is possible to outsource the merging process to PLINK as an intermediate solution.

**Comment by zhengxwen** [comment]
fix it in the [commit](https://github.com/zhengxwen/SNPRelate/commit/a1197feefcc5bd60db7f7b28bd0b0a5fa0db1fbc).
SNPRelate_v1.13.11
