### ISSUE TITLE
Method of handling missing data in snpgdsPCA

### ISSUE THREAD

**Issue by andemexoax** [zhengxwen/SNPRelate#81]
I'd like to know how missing genotypic data is handled in the function `snpgdsPCA`. I've reviewed the reference 
`Patterson N, Price AL, Reich D. Population structure and eigenanalysis. PLoS Genet. 2006 Dec;2(12):e190.`
but I am unable to find how missing data is handled. 

Are genotypes where data is missing all set to an arbitrary number like 3?

**Comment by zhengxwen** [comment]
The missing genotypes are imputed by the dosage mean.
The missing genotypes should be set to 3 in GDS.

**Comment by zhengxwen** [comment]
See the section of "Missing Data and Other Problems" in PLoS Genet. 2006 Dec;2(12):e190.
