### ISSUE TITLE
Labeling on HapMap Phase II

### ISSUE THREAD

**Issue by Asrix** [zhengxwen/SNPRelate#87]
Hi,

With snpgdsDrawTree is there any way to label the individuals? I would like to have the sample ids appear on the plot so I can tell which individuals it thinks are closely related.

Thanks!

**Comment by zhengxwen** [comment]
Yes. If you have a chance to take a look at the source code of `snpgdsDrawTree()`, the input of obj$dendrogram is a R dendrogram object. There are lots of examples to show how to customize the plot. .e.g., http://www.sthda.com/english/wiki/beautiful-dendrogram-visualizations-in-r-5-must-known-methods-unsupervised-machine-learning

**Comment by Asrix** [comment]
Thanks! I had tried looking at the plot documentation without much success.
