### ISSUE TITLE
Working with genome that has more than 23 chromosomes?

### ISSUE THREAD

**Issue by hsiaoyihung** [zhengxwen/SNPRelate#91]
Hi I am working with plants and there are cases my chromosome numbers are greater than 23 and the analysis I tried got cut off at 22. I was wondering is there anyways we can make it work? Thanks!

**Comment by zhengxwen** [comment]
Try `snpgdsPCA(, autosome.only=FALSE)`.

**Comment by hsiaoyihung** [comment]
> Try `snpgdsPCA(, autosome.only=FALSE)`.

That works, thank you so much!
