### ISSUE TITLE
transfer bed into gds

### ISSUE THREAD

**Issue by yywyaoyaowu** [zhengxwen/SNPRelate#92]
Hi 
I met this problem when I transfer bed into gds. I got the bed file from plink. is this the format problem? I got the bed file from plink. And I can get gum based on the bed file, the bed genotype should be ok. Thanks very much!

 snpgdsBED2GDS(bed.fn, fam.fn, bim.fn, "chr02_GATKFilterd.snp_367MR0.8_MAF001.gds")
Start file conversion from PLINK BED to SNP GDS ...
Error in (function (con, what, n = 1L, size = NA_integer_, signed = TRUE,  : 
  can only read from a binary connection
In addition: Warning message:
In file(filename, "rb") :
  file("") only supports open = "w+" and open = "w+b": using the former

**Comment by zhengxwen** [comment]
Please check `bed.fn`, `fam.fn` and `bim.fn`, they may be "".
