### ISSUE TITLE
SNPRelate does not check out on current R-Devel

### ISSUE THREAD

**Issue by green-striped-gecko** [zhengxwen/SNPRelate#94]
Hi, 
I am the maintainer of an R package (dartR) hosted on Cran and got the message that SNPRelate currently does not compile under R-devel. It was suggested to me to contact the maintainer if there is a chance that you would like to have a look at it and make the package work for current version of R-devel.   
So if there is any chance can you please let me know in the coming days, as otherwise I need to remove the dependency from our package (which would be a shame to loose the capabilities of your package).
Thanks in advance and kind regards,
Bernd

**Comment by zhengxwen** [comment]
I am working on this issue.

**Comment by green-striped-gecko** [comment]
Thanks, really appreciated.

Regards, Bernd



==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Professor Ecological Modelling                      \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: ***@***.******@***.***>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by zhengxwen** [comment]
The updated SNPRelate_v1.30.1 has been committed to BioC (release/devel both).
